### ISSUE TITLE
Running win percentages for the big four

### ISSUE THREAD

**Issue by rsibi** [ilangurudev/tennis_big4#1]
A graph that shows (from the beginning of their careers) win percentages for each of the four players.

y-axis : 0-100%
x-axis : number of matches played

**Comment by ilangurudev** [comment]
scatter plot?

**Comment by rsibi** [comment]
Wouldn't a line plot be better? It's a continuous plot (only one win% for every match played).

**Comment by ilangurudev** [comment]
I thought career win%. 
Win% here means, percentage of games won? If yes, there are about 700 - 1000 data points for each of the big4. Won't the lines be very jagged? Also, how are matches going to be arranged - by year?

**Comment by rsibi** [comment]
I'm guessing that initially, it'll jagged and it'll become smoother as number of matches increases. 

1. We could assume everyone beginning to play at the same time and plot the graph. 
2. Plot graph with the right scale for when they started playing (Federer first, Nadal next and so on).

**Comment by ilangurudev** [comment]
Okay, now I think I get it. Cumulative. I thought x-axis meant match number. I had both the axes wrong.

**Comment by rsibi** [comment]
Yes, cumulative. Put "running" instead.
