### ISSUE TITLE
atp_matches_all_new not working

### ISSUE THREAD

**Issue by ilangurudev** [ilangurudev/tennis_big4#2]
There was a parsing failure!

**Comment by rsibi** [comment]
Could you post a reprex please?

**Comment by ilangurudev** [comment]
```

library(tidyverse)
df_tennis <- read_csv("./data/atp_matches_all_new.csv")

```

**Comment by rsibi** [comment]
Thanks! Found out that the problem was with atp_matches_2017.csv. It had extraneous trailing commas. Have removed it and uploaded the atp_matches_all_new.csv file again. It should work now.

**Comment by ilangurudev** [comment]
Great! Thanks.
